#include <stdlib.h>
#include <string.h>
#include <stdio.h>

typedef int boolean;
#define true  1
#define false 0

typedef void (*Func)();

typedef struct _class_A _class_A;

struct _class_A{
   Func *vt;
};

_class_A *new_A(void);


typedef enum {_enum_A_m} _class_A_methods;

void _A_m( _class_A *this ){
   char __s[512];
   int _a0;
   int _a1;
   int _a2;
   int _a3;
   int _a4;
   int _a5;
   int _a6;
   int _a7;
   int _a8;
   int _a9;
   int _a10;
   int _a11;
   int _a12;
   int _a13;
   int _a14;
   int _a15;
   int _a16;
   int _a17;
   int _a18;
   int _a19;
   int _a20;
   int _a21;
   int _a22;
   int _a23;
   int _a24;
   int _a25;
   int _a26;
   int _a27;
   int _a28;
   int _a29;
   int _a30;
   int _a31;
   int _a32;
   int _a33;
   int _a34;
   int _a35;
   int _a36;
   int _a37;
   int _a38;
   int _a39;
   int _a40;
   int _a41;
   int _a42;
   int _a43;
   int _a44;
   int _a45;
   int _a46;
   int _a47;
   int _a48;
   int _a49;
   int _a50;
   int _a51;
   int _a52;
   int _a53;
   int _a54;
   int _a55;
   int _a56;
   int _a57;
   int _a58;
   int _a59;
   int _a60;
   int _a61;
   int _a62;
   int _a63;
   int _a64;
   int _a65;
   int _a66;
   int _a67;
   int _a68;
   int _a69;
   int _a70;
   int _a71;
   int _a72;
   int _a73;
   int _a74;
   int _a75;
   int _a76;
   int _a77;
   int _a78;
   int _a79;
   int _a80;
   int _a81;
   int _a82;
   int _a83;
   int _a84;
   int _a85;
   int _a86;
   int _a87;
   int _a88;
   int _a89;
   int _a90;
   int _a91;
   int _a92;
   int _a93;
   int _a94;
   int _a95;
   int _a96;
   int _a97;
   int _a98;
   int _a99;
   int _a100;
   int _a101;
   int _a102;
   int _a103;
   int _a104;
   int _a105;
   int _a106;
   int _a107;
   int _a108;
   int _a109;
   int _a110;
   int _a111;
   int _a112;
   int _a113;
   int _a114;
   int _a115;
   int _a116;
   int _a117;
   int _a118;
   int _a119;
   int _a120;
   int _a121;
   int _a122;
   int _a123;
   int _a124;
   int _a125;
   int _a126;
   int _a127;
   int _a128;
   int _a129;
   int _a130;
   int _a131;
   int _a132;
   int _a133;
   int _a134;
   int _a135;
   int _a136;
   int _a137;
   int _a138;
   int _a139;
   int _a140;
   int _a141;
   int _a142;
   int _a143;
   int _a144;
   int _a145;
   int _a146;
   int _a147;
   int _a148;
   int _a149;
   gets(__s);
   sscanf(__s,"%d",&_a0);
   sscanf(__s,"%d",&_a1);
   sscanf(__s,"%d",&_a2);
   sscanf(__s,"%d",&_a3);
   sscanf(__s,"%d",&_a4);
   sscanf(__s,"%d",&_a5);
   sscanf(__s,"%d",&_a6);
   sscanf(__s,"%d",&_a7);
   sscanf(__s,"%d",&_a8);
   sscanf(__s,"%d",&_a9);
   sscanf(__s,"%d",&_a10);
   sscanf(__s,"%d",&_a11);
   sscanf(__s,"%d",&_a12);
   sscanf(__s,"%d",&_a13);
   sscanf(__s,"%d",&_a14);
   sscanf(__s,"%d",&_a15);
   sscanf(__s,"%d",&_a16);
   sscanf(__s,"%d",&_a17);
   sscanf(__s,"%d",&_a18);
   sscanf(__s,"%d",&_a19);
   sscanf(__s,"%d",&_a20);
   sscanf(__s,"%d",&_a21);
   sscanf(__s,"%d",&_a22);
   sscanf(__s,"%d",&_a23);
   sscanf(__s,"%d",&_a24);
   sscanf(__s,"%d",&_a25);
   sscanf(__s,"%d",&_a26);
   sscanf(__s,"%d",&_a27);
   sscanf(__s,"%d",&_a28);
   sscanf(__s,"%d",&_a29);
   sscanf(__s,"%d",&_a30);
   sscanf(__s,"%d",&_a31);
   sscanf(__s,"%d",&_a32);
   sscanf(__s,"%d",&_a33);
   sscanf(__s,"%d",&_a34);
   sscanf(__s,"%d",&_a35);
   sscanf(__s,"%d",&_a36);
   sscanf(__s,"%d",&_a37);
   sscanf(__s,"%d",&_a38);
   sscanf(__s,"%d",&_a39);
   sscanf(__s,"%d",&_a40);
   sscanf(__s,"%d",&_a41);
   sscanf(__s,"%d",&_a42);
   sscanf(__s,"%d",&_a43);
   sscanf(__s,"%d",&_a44);
   sscanf(__s,"%d",&_a45);
   sscanf(__s,"%d",&_a46);
   sscanf(__s,"%d",&_a47);
   sscanf(__s,"%d",&_a48);
   sscanf(__s,"%d",&_a49);
   sscanf(__s,"%d",&_a50);
   sscanf(__s,"%d",&_a51);
   sscanf(__s,"%d",&_a52);
   sscanf(__s,"%d",&_a53);
   sscanf(__s,"%d",&_a54);
   sscanf(__s,"%d",&_a55);
   sscanf(__s,"%d",&_a56);
   sscanf(__s,"%d",&_a57);
   sscanf(__s,"%d",&_a58);
   sscanf(__s,"%d",&_a59);
   sscanf(__s,"%d",&_a60);
   sscanf(__s,"%d",&_a61);
   sscanf(__s,"%d",&_a62);
   sscanf(__s,"%d",&_a63);
   sscanf(__s,"%d",&_a64);
   sscanf(__s,"%d",&_a65);
   sscanf(__s,"%d",&_a66);
   sscanf(__s,"%d",&_a67);
   sscanf(__s,"%d",&_a68);
   sscanf(__s,"%d",&_a69);
   sscanf(__s,"%d",&_a70);
   sscanf(__s,"%d",&_a71);
   sscanf(__s,"%d",&_a72);
   sscanf(__s,"%d",&_a73);
   sscanf(__s,"%d",&_a74);
   sscanf(__s,"%d",&_a75);
   sscanf(__s,"%d",&_a76);
   sscanf(__s,"%d",&_a77);
   sscanf(__s,"%d",&_a78);
   sscanf(__s,"%d",&_a79);
   sscanf(__s,"%d",&_a80);
   sscanf(__s,"%d",&_a81);
   sscanf(__s,"%d",&_a82);
   sscanf(__s,"%d",&_a83);
   sscanf(__s,"%d",&_a84);
   sscanf(__s,"%d",&_a85);
   sscanf(__s,"%d",&_a86);
   sscanf(__s,"%d",&_a87);
   sscanf(__s,"%d",&_a88);
   sscanf(__s,"%d",&_a89);
   sscanf(__s,"%d",&_a90);
   sscanf(__s,"%d",&_a91);
   sscanf(__s,"%d",&_a92);
   sscanf(__s,"%d",&_a93);
   sscanf(__s,"%d",&_a94);
   sscanf(__s,"%d",&_a95);
   sscanf(__s,"%d",&_a96);
   sscanf(__s,"%d",&_a97);
   sscanf(__s,"%d",&_a98);
   sscanf(__s,"%d",&_a99);
   sscanf(__s,"%d",&_a100);
   sscanf(__s,"%d",&_a101);
   sscanf(__s,"%d",&_a102);
   sscanf(__s,"%d",&_a103);
   sscanf(__s,"%d",&_a104);
   sscanf(__s,"%d",&_a105);
   sscanf(__s,"%d",&_a106);
   sscanf(__s,"%d",&_a107);
   sscanf(__s,"%d",&_a108);
   sscanf(__s,"%d",&_a109);
   sscanf(__s,"%d",&_a110);
   sscanf(__s,"%d",&_a111);
   sscanf(__s,"%d",&_a112);
   sscanf(__s,"%d",&_a113);
   sscanf(__s,"%d",&_a114);
   sscanf(__s,"%d",&_a115);
   sscanf(__s,"%d",&_a116);
   sscanf(__s,"%d",&_a117);
   sscanf(__s,"%d",&_a118);
   sscanf(__s,"%d",&_a119);
   sscanf(__s,"%d",&_a120);
   sscanf(__s,"%d",&_a121);
   sscanf(__s,"%d",&_a122);
   sscanf(__s,"%d",&_a123);
   sscanf(__s,"%d",&_a124);
   sscanf(__s,"%d",&_a125);
   sscanf(__s,"%d",&_a126);
   sscanf(__s,"%d",&_a127);
   sscanf(__s,"%d",&_a128);
   sscanf(__s,"%d",&_a129);
   sscanf(__s,"%d",&_a130);
   sscanf(__s,"%d",&_a131);
   sscanf(__s,"%d",&_a132);
   sscanf(__s,"%d",&_a133);
   sscanf(__s,"%d",&_a134);
   sscanf(__s,"%d",&_a135);
   sscanf(__s,"%d",&_a136);
   sscanf(__s,"%d",&_a137);
   sscanf(__s,"%d",&_a138);
   sscanf(__s,"%d",&_a139);
   sscanf(__s,"%d",&_a140);
   sscanf(__s,"%d",&_a141);
   sscanf(__s,"%d",&_a142);
   sscanf(__s,"%d",&_a143);
   sscanf(__s,"%d",&_a144);
   sscanf(__s,"%d",&_a145);
   sscanf(__s,"%d",&_a146);
   sscanf(__s,"%d",&_a147);
   sscanf(__s,"%d",&_a148);
   sscanf(__s,"%d",&_a149);
   printf("%d",_a0);
   printf("%d",_a1);
   printf("%d",_a2);
   printf("%d",_a3);
   printf("%d",_a4);
   printf("%d",_a5);
   printf("%d",_a6);
   printf("%d",_a7);
   printf("%d",_a8);
   printf("%d",_a9);
   printf("%d",_a10);
   printf("%d",_a11);
   printf("%d",_a12);
   printf("%d",_a13);
   printf("%d",_a14);
   printf("%d",_a15);
   printf("%d",_a16);
   printf("%d",_a17);
   printf("%d",_a18);
   printf("%d",_a19);
   printf("%d",_a20);
   printf("%d",_a21);
   printf("%d",_a22);
   printf("%d",_a23);
   printf("%d",_a24);
   printf("%d",_a25);
   printf("%d",_a26);
   printf("%d",_a27);
   printf("%d",_a28);
   printf("%d",_a29);
   printf("%d",_a30);
   printf("%d",_a31);
   printf("%d",_a32);
   printf("%d",_a33);
   printf("%d",_a34);
   printf("%d",_a35);
   printf("%d",_a36);
   printf("%d",_a37);
   printf("%d",_a38);
   printf("%d",_a39);
   printf("%d",_a40);
   printf("%d",_a41);
   printf("%d",_a42);
   printf("%d",_a43);
   printf("%d",_a44);
   printf("%d",_a45);
   printf("%d",_a46);
   printf("%d",_a47);
   printf("%d",_a48);
   printf("%d",_a49);
   printf("%d",_a50);
   printf("%d",_a51);
   printf("%d",_a52);
   printf("%d",_a53);
   printf("%d",_a54);
   printf("%d",_a55);
   printf("%d",_a56);
   printf("%d",_a57);
   printf("%d",_a58);
   printf("%d",_a59);
   printf("%d",_a60);
   printf("%d",_a61);
   printf("%d",_a62);
   printf("%d",_a63);
   printf("%d",_a64);
   printf("%d",_a65);
   printf("%d",_a66);
   printf("%d",_a67);
   printf("%d",_a68);
   printf("%d",_a69);
   printf("%d",_a70);
   printf("%d",_a71);
   printf("%d",_a72);
   printf("%d",_a73);
   printf("%d",_a74);
   printf("%d",_a75);
   printf("%d",_a76);
   printf("%d",_a77);
   printf("%d",_a78);
   printf("%d",_a79);
   printf("%d",_a80);
   printf("%d",_a81);
   printf("%d",_a82);
   printf("%d",_a83);
   printf("%d",_a84);
   printf("%d",_a85);
   printf("%d",_a86);
   printf("%d",_a87);
   printf("%d",_a88);
   printf("%d",_a89);
   printf("%d",_a90);
   printf("%d",_a91);
   printf("%d",_a92);
   printf("%d",_a93);
   printf("%d",_a94);
   printf("%d",_a95);
   printf("%d",_a96);
   printf("%d",_a97);
   printf("%d",_a98);
   printf("%d",_a99);
   printf("%d",_a100);
   printf("%d",_a101);
   printf("%d",_a102);
   printf("%d",_a103);
   printf("%d",_a104);
   printf("%d",_a105);
   printf("%d",_a106);
   printf("%d",_a107);
   printf("%d",_a108);
   printf("%d",_a109);
   printf("%d",_a110);
   printf("%d",_a111);
   printf("%d",_a112);
   printf("%d",_a113);
   printf("%d",_a114);
   printf("%d",_a115);
   printf("%d",_a116);
   printf("%d",_a117);
   printf("%d",_a118);
   printf("%d",_a119);
   printf("%d",_a120);
   printf("%d",_a121);
   printf("%d",_a122);
   printf("%d",_a123);
   printf("%d",_a124);
   printf("%d",_a125);
   printf("%d",_a126);
   printf("%d",_a127);
   printf("%d",_a128);
   printf("%d",_a129);
   printf("%d",_a130);
   printf("%d",_a131);
   printf("%d",_a132);
   printf("%d",_a133);
   printf("%d",_a134);
   printf("%d",_a135);
   printf("%d",_a136);
   printf("%d",_a137);
   printf("%d",_a138);
   printf("%d",_a139);
   printf("%d",_a140);
   printf("%d",_a141);
   printf("%d",_a142);
   printf("%d",_a143);
   printf("%d",_a144);
   printf("%d",_a145);
   printf("%d",_a146);
   printf("%d",_a147);
   printf("%d",_a148);
   printf("%d",_a149);
}

Func VTclass_A[] = {
   ( void (*)() ) _A_m
};

_class_A *new_A(){
   _class_A *t;
   if ( (t = malloc(sizeof(_class_A))) != NULL )
      t->vt = VTclass_A;
   return t;
}

typedef struct _class_Program _class_Program;

struct _class_Program{
   Func *vt;
};

_class_Program *new_Program(void);


typedef enum {_enum_Program_run} _class_Program_methods;

void _Program_run( _class_Program *this ){
   _class_A *_a;
   _a = new_A();
   ( ( ( void (*)(_class_A * ) ) _a->vt[_enum_A_m] )( _a) );
}

Func VTclass_Program[] = {
   ( void (*)() ) _Program_run
};

_class_Program *new_Program(){
   _class_Program *t;
   if ( (t = malloc(sizeof(_class_Program))) != NULL )
      t->vt = VTclass_Program;
   return t;
}

int main() {
   _class_Program *program;
   program = new_Program();
   ( ( void (*)(_class_Program *) ) program->vt[0] )(program);
   return 0;
}